markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Nicholas Zaillian
url: http://blog.nicholas.zaillian.com
description: Nicholas Zaillian's blog. My primary home page is at http://nicholas.zaillian.com
github: nzaillian
gravatar_url: /images/avatar-sm.png
twitter: nzaillian